[package]
name = "emigui-miniquad"
version = "0.1.0"
authors = ["Logachev Fedor <not.fl3@gmail.com >"]
edition = "2018"

[features]
macroquad-plugin = ["macroquad", "quad-gl"]

[dependencies]
miniquad = { version = "=0.3.0-alpha.11" }
egui = "0.1.3"
quad-gl = { version = "0.2.3", optional = true }
# macroquad = { version = "0.2.9", optional = true }
macroquad = { path = "../macroquad", optional = true }
