[package]
name = "emigui-miniquad"
version = "0.1.0"
authors = ["Logachev Fedor <not.fl3@gmail.com >"]
edition = "2018"

[[example]]
name = "shop"
required-features = [ "macroquad" ]

[dependencies]
miniquad = { version = "=0.3.0-alpha.11" }
egui = "0.1.4"

[dependencies.macroquad]
git = "https://github.com/cedric-h/macroquad"
branch = "char_events"
optional = true
